#!/usr/bin/env python3
"""
Assemble the 17 chapter lectures into a single book: book.tex -> book.pdf.

Combining the per-chapter lecture PDFs does not read as a book: each one carries
its own title page and its own page numbering. This assembler instead stitches
the lecture *markdown* into one \\documentclass{book} document with a single
title page, a table of contents, one \\part per curriculum phase, one \\chapter
per lecture, continuous pagination, and running heads.

It reuses the deterministic markdown -> LaTeX machinery in render_tex.py, so the
book and the per-document print layer can never drift in how they convert a
given paragraph. Together with render_tex.py this is the only producer of .tex
in the repository. Never hand-edit book.tex.

Only the lecture.md of each chapter is included (the lecture is the book's prose;
notes/exercises/quiz/assignment are workbook artifacts, not chapter text).

    make book        assemble book.tex and compile book.pdf
    python3 render_book.py   assemble book.tex only
"""

import json
import os
import re

import render_tex as rt

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHAPTERS_DIR = os.path.join(BASE_DIR, "chapters")
BUILD_DIR = os.path.join(BASE_DIR, "build")

BOOK_TITLE = "The Structure of Mathematical Reality"
BOOK_SUBTITLE = "A Navigational Map of the Foundations"
BOOK_TAGLINE = "Foundations, structure, and why mathematics connects to the world"

PREAMBLE = r"""% AUTO-GENERATED by render_book.py from the chapter lecture.md files. DO NOT EDIT.
% Edit the chapter lectures or curriculum.md, then run: make book
\documentclass[11pt,oneside]{book}
\usepackage{smr-style}

% smr-style configures article-style headers keyed to a single chapter number.
% Replace them with book running heads driven by the \chapter marks.
\fancyhf{}
\fancyhead[L]{\small\textcolor{smrGray}{\leftmark}}
\fancyhead[R]{\small\textcolor{smrGray}{The Structure of Mathematical Reality}}
\fancyfoot[C]{\small\textcolor{smrGray}{\thepage}}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\chaptermark}[1]{\markboth{Chapter \thechapter.\ #1}{}}

% Chapter and part openers in the curriculum palette.
\titleformat{\chapter}[display]
    {\normalfont\bfseries\color{smrDark}}
    {\Large\color{smrGray}\chaptertitlename\ \thechapter}{0.4em}{\Huge}
\titleformat{\part}[display]
    {\normalfont\centering}
    {\Large\color{smrGray}\partname\ \thepart}{0.6em}{\Huge\bfseries\color{smrDark}}

% Chapters and parts numbered; internal subheads stay unnumbered and out of the
% table of contents (there are many per chapter).
\setcounter{secnumdepth}{0}
\setcounter{tocdepth}{0}

\begin{document}
\frontmatter

\begin{titlepage}
    \centering
    \vspace*{3cm}
    {\small\textcolor{smrGray}{A SELF-STUDY CURRICULUM}\par}
    \vspace{1.5cm}
    {\Huge\bfseries\textcolor{smrDark}{@@TITLE@@}\par}
    \vspace{1cm}
    {\Large\textcolor{smrBlue}{@@SUBTITLE@@}\par}
    \vspace{\fill}
    {\small\textcolor{smrGray}{@@TAGLINE@@}\par}
\end{titlepage}

\tableofcontents

\mainmatter
"""


def build_book():
    folders = sorted(
        d for d in os.listdir(CHAPTERS_DIR)
        if re.match(r"ch\d{2}-", d) and os.path.isdir(os.path.join(CHAPTERS_DIR, d))
    )

    parts = [
        PREAMBLE
        .replace("@@TITLE@@", rt.inline(BOOK_TITLE))
        .replace("@@SUBTITLE@@", rt.inline(BOOK_SUBTITLE))
        .replace("@@TAGLINE@@", rt.inline(BOOK_TAGLINE))
    ]

    current_phase = None
    for folder in folders:
        meta = json.load(open(os.path.join(CHAPTERS_DIR, folder, "metadata.json"), encoding="utf-8"))

        if meta["phase"] != current_phase:
            parts.append("\n\\part{" + rt.inline(meta["phase_title"]) + "}\n")
            current_phase = meta["phase"]

        src = os.path.join(CHAPTERS_DIR, folder, "lecture.md")
        text = open(src, encoding="utf-8").read()
        body_md = rt.strip_generated_header(text)
        rendered = rt.render_blocks(rt.parse_blocks(body_md))
        # Under \chapter, promote the lecture's bold subheads (rendered as
        # \subsection*) to \section* so they sit directly beneath the chapter.
        # Lecture bodies contain no markdown ### headings, so every \subsection*
        # here originates from a bold subhead.
        rendered = rendered.replace(r"\subsection*{", r"\section*{")

        parts.append(r"\chapter{" + rt.inline(meta["title"]) + "}")
        parts.append(rendered)
        parts.append("")

    parts.append("\\end{document}\n")
    return "\n".join(parts)


def main():
    tex = build_book()
    os.makedirs(BUILD_DIR, exist_ok=True)
    out = os.path.join(BUILD_DIR, "book.tex")
    with open(out, "w", encoding="utf-8") as f:
        f.write(tex)
    print(f"  wrote book.tex ({tex.count(chr(10))} lines) from 17 chapter lectures")


if __name__ == "__main__":
    main()
